### ISSUE TITLE
Tolong Tambahkan Getter Untuk Variable private $response pada Notification

### ISSUE THREAD

**Issue by ifaniqbal** [Midtrans/midtrans-php#10]
Dengan begitu, kita bisa langsung dump nilai-nilainya menjadi JSON untuk disimpan ke database.

**Comment by rizdaprasetya** [comment]
Good idea, akan kita consider untuk tambahkan ya

**Comment by rizdaprasetya** [comment]
added ya @ifaniqbal https://github.com/Midtrans/midtrans-php/commit/4c5bbe32e26a4cd9c9d1460c91fd7270a57b9f4d
Silahkan dicoba `$notification->getResponse()`
