### ISSUE TITLE
tidak bisa memuat ulang snap untuk memunculkan kode QR gopay

### ISSUE THREAD

**Issue by abdulauliya** [Midtrans/midtrans-php#15]
Setelah memilih metode pembayaran gopay dan status pembayaran menjadi PENDING, user tidak sengaja merefresh halaman. ketika halaman dimuat dan snap muncul kembali, user tidak bisa melihat QR code untuk menyelesaikan pembayaran. Metode seperti apa untuk menangani masalah ini? trims
![gopay](https://user-images.githubusercontent.com/61233567/74831784-7ee66300-5348-11ea-8933-6c49c6991583.png)

**Comment by rizdaprasetya** [comment]
Hi @abdulauliya untuk case ini memang saat ini di Snap belum di handle, jadi QR code belum bisa di-retrieve ulang. Workaroundnya bisa dengan call API `/cancel` pada order-id tersebut, kemudian create ulang transaksi.

Pada produk Core API, QR image URL akan bisa diretrieve sebagai API response. Untuk Snap belum bisa.

**Comment by rizdaprasetya** [comment]
Closed due to inactivity, please comment if you need further assistance

**Comment by Firman95** [comment]
Di Core API, response dari `/charge` bisa dapat attribute `actions`. Apakah ada cara lain untuk mendapatkan isi dari attribute `actions` selain dari `/charge`?

**Comment by Firman95** [comment]
@rizdaprasetya sebelumnya disebutkan workaround dengan call api cancel pada order id tersebut, kemudian create ulang transaksi. apakah create ulang transaksi bisa menggunakan order id yang sama?

**Comment by rizdaprasetya** [comment]
hi @Firman95  Untuk detailnya silahkan refer ke bagian dokumentasi berikut, khusus untuk membahas case sejenis ini:
https://docs.midtrans.com/en/snap/advanced-feature?id=allowing-customer-to-re-pay-the-same-order
terima kasih

**Comment by ayamgoreng47** [comment]
apakah untuk saat ini penggunaan snap sudah memungkinkan? Sebab masih terdapat snap error jika payment menggunakan gojek, pak.

> hi @Firman95 Untuk detailnya silahkan refer ke bagian dokumentasi berikut, khusus untuk membahas case sejenis ini: https://docs.midtrans.com/en/snap/advanced-feature?id=allowing-customer-to-re-pay-the-same-order terima kasih

**Comment by khoirul2009** [comment]
@rizdaprasetya cara dapeting kode QR lagi pas transaksi masih pending gimana ya? saya pake Core API
