### ISSUE TITLE
[Error 413] Payload Format is not supported.

### ISSUE THREAD

**Issue by quetzalcroix** [Midtrans/midtrans-php#18]
Hi, I have some issue with this error.

When I'm using the Midtrans sample-uikit for android to test the Midtrans in my local server. I followed the [documentation for mobile SDK](https://mobile-docs.midtrans.com/) and setting up my PHP [Laravel](https://laravel.com) to accept the request from mobile SDK.

I'm using PHP 7.2 (Downgraded from 7.4) and below is the screenshots

### Post Request from INSOMNIA
![image](https://user-images.githubusercontent.com/5761531/76812528-c10ba300-6827-11ea-8831-9c1518589279.png)

### Charge Controller
![image](https://user-images.githubusercontent.com/5761531/76812644-1d6ec280-6828-11ea-8c89-5de4614fd8c7.png)

**Comment by quetzalcroix** [comment]
Doesn't matter, I have resolved this :)

**Comment by rizdaprasetya** [comment]
hi @quetzalcroix 
The issue most likely is the parameter you used for `CoreApi::charge()`.
Please dump/debug/print out what is the value you are passing to that function (the value of `$request->toArray()`)
And post it here

**Comment by rizdaprasetya** [comment]
Oops sorry, didnt read the above comment.
