### ISSUE TITLE
Override notification URL

### ISSUE THREAD

**Issue by imiro** [Midtrans/midtrans-php#20]
Hi,

The snap docs state that we are able to override/append default notification url by modifying header in the charge request. Can we do that using this library?

Since from what I understand, the Http request is taken care of by the library using cURL.

Thanks!

**Comment by rizdaprasetya** [comment]
Not for now.
We are planning to add that new capability to set HTTP headers soon.

**Comment by imiro** [comment]
I see. Alrigth then, thanks for the answer. Looking forward into that!

**Comment by rizdaprasetya** [comment]
Yes we are trying to make it happen as soon as we are availble, will keep this issue open as reminder. Thanks!

**Comment by balydeg** [comment]
Hi, I get an error when request status
`$status = \Midtrans\Transaction::status($order->no_order);
var_dump($status);`
![Screenshot_1](https://user-images.githubusercontent.com/3423247/81644455-f6acc100-9451-11ea-96b8-11bc967135fc.jpg)

**Comment by rizdaprasetya** [comment]
Hi @imiro sorry for the delay, we have implemented this on latest v2.3
https://github.com/Midtrans/midtrans-php/releases/tag/v2.3.0
Thanks!

**Comment by rizdaprasetya** [comment]
Usage instruction:
https://github.com/Midtrans/midtrans-php#override-notification-url
