### ISSUE TITLE
Error Get Transaction Status

### ISSUE THREAD

**Issue by balydeg** [Midtrans/midtrans-php#21]
Hi, I get an error when request status
`$status = \Midtrans\Transaction::status($order->no_order); var_dump($status);`
![Screenshot_1](https://user-images.githubusercontent.com/3423247/81645123-33c58300-9453-11ea-8042-02a6bbf7cb65.jpg)

**Comment by rizdaprasetya** [comment]
Do you have more detailed error log?
Looks like your host unable to contact Midtrans API, please make sure:
- your host able to connect to internet & *.midtrans.com API
- you set correct serverkey & is_production
- `$order->no_order` have valid value that already created on Midtrans side as transaction

**Comment by balydeg** [comment]
Of course I already have API connection to midtrans.
Request snap token succeeded and there is no problems.
Only request status and canceling transaction have an error

This is my code when checking the status:

`class Trans extends CI_Controller {	
	function __construct(){
		parent::__construct();
		require APPPATH.'third_party/Midtrans/Midtrans.php';
		\Midtrans\Config::$serverKey = 'xxxxxxxxxxxxxxxxxxxx';
		\Midtrans\Config::$isProduction = false;
		\Midtrans\Config::$isSanitized = true;
		\Midtrans\Config::$is3ds = true;		
	}
	
	public function get_status(){
		$status = \Midtrans\Transaction::status('INV/200512/000082');
		var_dump($status);
	}	
}`

Error Capture:
![Screenshot_5](https://user-images.githubusercontent.com/3423247/81672032-c83fdd80-9473-11ea-9060-6acd38852859.jpg)

**Comment by Xaxxis** [comment]
You need change you order-id without `/` character. We don't recommend order-id separate with `/` or you can change with `-` @balydeg

**Comment by balydeg** [comment]
Thanks @Xaxxis , the problem was solved
