### ISSUE TITLE
Bisakah menguji notifikasi pada localhost

### ISSUE THREAD

**Issue by hilmanrdn** [Midtrans/midtrans-php#23]
halo, Apakah ada cara menguji notifikasi pada localhost? 
simulasi ketika berhasil, dll/

salam, terima kasih

**Comment by Xaxxis** [comment]
Hi @hilmanrdn anda bisa menghubungkan aplikasi localhost anda agar dapat diakses melalui Internet, salah satunya menggunakan [Ngrok](https://ngrok.com/). Serta mengisi URL ngrok-domain+path-to-your-notif-controller ke halaman notif configuration pada Dashboard Midtrans

Semoga membantu, Terima kasih

**Comment by hilmanrdn** [comment]
> Hi @hilmanrdn anda bisa menghubungkan aplikasi localhost anda agar dapat diakses melalui Internet, salah satunya menggunakan [Ngrok](https://ngrok.com/). Serta mengisi URL ngrok-domain+path-to-your-notif-controller ke halaman notif configuration pada Dashboard Midtrans
> 
> Semoga membantu, Terima kasih

ohiya, betul juga. terima kasih jawabannya
