### ISSUE TITLE
Snap Issue: transaction_details.gross_amount replaced by the sum of item_details

### ISSUE THREAD

**Issue by Fq2112** [Midtrans/midtrans-php#25]
Kenapa value dari transaction_details.gross_amount selalu ke-replace oleh total value dari item_details? Karna kasus saya perlu menambahkan shipping cost di gross_amount sehingga terdapat selisih value antara gross_amount dan item_details.. tetapi ketika request snap, amount nya selalu tergantikan oleh item_details tersebut, shipping costnya hilang..

**Comment by Fq2112** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/19623652/85062022-fe3e5300-b1d1-11ea-81ab-2e7feea35955.png)

**Comment by Xaxxis** [comment]
Hi @Fq2112  thank you for reaching out to us, sayangnya hal tersebut memang bukanlah issue. Untuk menambahkan shipping cost pada gross_amount, anda perlu menambahkan shipping cost sebagai items juga ke dalam object `item_details`. Snap tidak mempunyai object khusus untuk put shipping cost. Secara default Plugins Midtrans-php juga tidak melakukan calculate total items-details secara otomatis, kemungkinan yang mereplace sendiri gross-amount tersebut terdapat pada code milik merchant, dari Midtrans hanya akan meresponse dengan message `"transaction_details.gross_amount is not equal to the sum of item_details"` jika ada ketidak samaan jumlah `gross_amount` dengan total i`tem_details`

Anda dapat mengunjungi halaman [dokumentasi Snap](https://snap-docs.midtrans.com/#request-body-json-parameter) untuk detail body request Snap. Semoga membantu

Terima kasih

**Comment by Fq2112** [comment]
@Xaxxis oohh custom field 1,2,3 dst.. itu ya?

**Comment by Fq2112** [comment]
Ok sudah bisa, thx @Xaxxis

**Comment by husna3305** [comment]
bagaimana dengan diskon ?

**Comment by husna3305** [comment]
saya bermasalah dengan perhitungan diskon

**Comment by Arezafaza16** [comment]
> Hi @Fq2112 thank you for reaching out to us, sayangnya hal tersebut memang bukanlah issue. Untuk menambahkan shipping cost pada gross_amount, anda perlu menambahkan shipping cost sebagai items juga ke dalam object `item_details`. Snap tidak mempunyai object khusus untuk put shipping cost. Secara default Plugins Midtrans-php juga tidak melakukan calculate total items-details secara otomatis, kemungkinan yang mereplace sendiri gross-amount tersebut terdapat pada code milik merchant, dari Midtrans hanya akan meresponse dengan message `"transaction_details.gross_amount is not equal to the sum of item_details"` jika ada ketidak samaan jumlah `gross_amount` dengan total i`tem_details`
> 
> Anda dapat mengunjungi halaman [dokumentasi Snap](https://snap-docs.midtrans.com/#request-body-json-parameter) untuk detail body request Snap. Semoga membantu
> 
> Terima kasih

masalahnya, metode kaya gini bakal ngehasilin shipping cost di semua item, sementara di real case nya shipping cost itu total harga dari semua item baru ditambahkan dengan shipping cost. Apakah tidak ada solusi lain?

**Comment by MrBenighin** [comment]
@Xaxxis saya juga masih bermasalah dengan diskon

**Comment by kikikiswanto** [comment]
Apakah tidak ada solusi untuk diskon ?
case saya seperti ini
{"item_details": [{"id": "FTDY8MKR9", "name": "Nama barang, diskon 500", "price": 5000, "quantity": 1, "total": 4500}], "transaction_details": {"gross_amount": 4500, "order_id": "251208U03VJ", "qty": 1}, "user_id": "Nama User"}
secara total dan gross amount jumlahnya sudah sama tapi masih error, sepertinya logic nya masih menghitung price dan quantity, bukan ambil dari total ya.

**Comment by kikikiswanto** [comment]
> {"item_details": [{"id": "FTDY8MKR9", "name": "Nama barang, diskon 500", "price": 5000, "quantity": 1, "total": 4500}], "transaction_details": {"gross_amount": 4500, "order_id": "251208U03VJ", "qty": 1}, "user_id": "Nama User"}

solusi alternatif nya tambahkan satu item untuk mengurangi total dengan discount : price nya minus, qty 1.
contoh
{"item_details": [{"id": "FTDY8MKR9", "name": "Nama barang, diskon 500", "price": 5000, "quantity": 1, "total": 4500}, {"id": "FTDY8MKR9-DISC", "name": "diskon -500", "price": -500, "quantity": 1}], "transaction_details": {"gross_amount": 4500, "order_id": "251208U03VJ", "qty": 1}, "user_id": "Nama User"}
