### ISSUE TITLE
array_key_exists is deprecated in PHP 7.4 same as closed issue in #6

### ISSUE THREAD

**Issue by reapera** [Midtrans/midtrans-php#28]
still have array_key_exists on v2.3.0 please help ya
https://github.com/Midtrans/midtrans-php/blob/v2.3.0/Midtrans/Snap.php#L65
https://github.com/Midtrans/midtrans-php/issues/6

**Comment by rizdaprasetya** [comment]
Hi @reapera thanks for reporting. it's been fixed by @Xaxxis  here 
https://github.com/Midtrans/midtrans-php/pull/29
Has been merged & released as new `v2.3.1` please check. And let us know if you see any issue. Thanks!

**Comment by rizdaprasetya** [comment]
wait, @Xaxxis looks like there were still some of it:
https://github.com/Midtrans/midtrans-php/search?q=array_key_exists&unscoped_q=array_key_exists

please help check and patch. thanks

**Comment by rizdaprasetya** [comment]
Fixed by @Xaxxis and realeased as `v2.3.2` now. Thanks.

**Comment by reapera** [comment]
Thanks! will try it now
