### ISSUE TITLE
Menyeragamkan format response variable hasil snap.pay() dengan \Midtrans\Notification()

### ISSUE THREAD

**Issue by adeindriawan** [Midtrans/midtrans-php#33]
Ketika snap.pay() berhasil dijalankan dan berstatus onPending, browser menerima response object, salah satu key dalam object tersebut yaitu "pdf_url". Ketika transaksi berstatus pending, server juga menerima notifikasi. Dalam response object hasil dari Notification(), key "pdf_url" tersebut tidak ada, padahal nilai di dalamnya penting untuk disimpan ke dalam database karena bersifat unik.

Sebenarnya bisa menggunakan nilai pdf_url dari browser tadi yang dikirim lagi ke server lewat AJAX, namun itu berarti melakukan 2 kali query ke database untuk order ID yang sama.

**Comment by rizdaprasetya** [comment]
Untuk saat ini memang by design HTTP Notification tidak include value `pdf_url`. Karena `pdf_url` umumnya relevant untuk di bagian frontend ketika menampilkan cara pembayaran ke customer. Jika memang ingin menyimpan valuenya, silahkan untuk sekarang disimpan dari frontend callback tersebut.
