### ISSUE TITLE
Blank Saat Create Token

### ISSUE THREAD

**Issue by maulayyacyber** [Midtrans/midtrans-php#34]
saya ada permasalahan ketika membuat token di online menjadi blank, akan tetapi di localhost bisa berjalan dengan baik, beikut kode yang saya buat

`use Midtrans\Snap;`

```
// Buat transaksi ke midtrans kemudian save snap tokennya.
            $payload = [
                'transaction_details' => [
                    'order_id'      => $invoice,
                    'gross_amount'  => $transaction->price,
                ],
                'customer_details' => [
                    'first_name'    => auth()->user()->name,
                    'email'         => auth()->user()->email,
                ],
                'item_details' => [
                    [
                        'id'       => $transaction->id,
                        'price'    => $transaction->price,
                        'quantity' => 1,
                        'name'     => $tutorial_set_premium->title
                    ]
                ]
            ];

            //create snap token
            $snapToken = Snap::getSnapToken($payload);
            dd($snapToken);
```

**Comment by rizdaprasetya** [comment]
Hi @maulayyacyber 
Jika codenya sama tapi hasilnya berbeda di machine/env yg berbeda, silahkan cek hal berikut yg sering terjadi:
- Make sure di environment online/hosting/VPS/machine tersebut bisa reach ke internet, terutama API midtrans. 
- Cek di error log, apakah ada message error tertentu yg bisa membantu debugging.
- Make sure value variable config sudah sesuai, silahkan cek apakah var serverKey, clientKey, isProduction sudah berisi value yg benar atau null.
- Make sure value parameter data transaksi tidak ada yg bernilai null, sama seperti di atas.

Dari kami sendiri tidak bisa bantu cek langsung ke environment Anda, karena hanya Anda yg punya dan bisa akses hal-hal di atas. Thanks.

**Comment by maulayyacyber** [comment]
terima kasih, sudah solve

ternyata belum install php curl di server.

mungkin di doc perlu di tambahkan kebutuhan librray atau extension yang harus dibutuhkan

**Comment by rizdaprasetya** [comment]
Oke, terima kasih konfirmasinya.

Sebenarnya sudah di handle di code berikut:
https://github.com/Midtrans/midtrans-php/blob/e65e1e81524bae5f91de5071fe609ac7ca24fc7c/Midtrans.php#L10-L15

Oleh karena itu akan muncul (dan sebaiknya cek) di error log nya.
