### ISSUE TITLE
Null response in production mode

### ISSUE THREAD

**Issue by cierish** [Midtrans/midtrans-php#35]
Hi,

We change from sandbox into production using core API and connect to php, but it doesn't work. 
We get null response from Midtrans server. We already set isProduction and change the server key.

Using Sandbox is absolutely no problem.

What could be the problem?

Many thanks.

Cheers,
Cherry

**Comment by Xaxxis** [comment]
Hi @cierish thank you for interested with Midtrans

For further check, we need the details about the response from our server / Our PHP library. Do you have more detailed error log?

Regards

**Comment by cierish** [comment]
Hi @Xaxxis thank you for your reply.

Our gopay payment request gets null response and causes Volley error in production mode.
The volley error code is [Volley]: [7753] BasicNetwork.performRequest: Unexpected response code 500. 

Meanwhile, we've also sent support to Midtrans.

Eventually, the problem is caused by the account, which is not fully activated yet. Although, we have completed our documents for activation, on 2nd of September. We are still waiting for the confirmation.

Many thanks.

Cheers,
Cherry

**Comment by Xaxxis** [comment]
Hi @cierish thank you for the details, since you already sent the issue to our support team. Will close this issue and please wait for the update from our support team via email

Regards
