### ISSUE TITLE
SESSION tersimpan hilang setelah redirect dari "sukses/finish" pembayaran

### ISSUE THREAD

**Issue by sorryjack** [Midtrans/midtrans-php#36]
halo, saya sedang mode sandbox, mencoba melakukan pembelian melalui BCA Klik pay. Setelah pembayaran sukses, redirect ke halaman sukses kan, tapi kenapa SESSION saya jadi hilang semua ya 

mohon bantuannya, apakah error di saya, apakah di production nanti tidak begitu?

terima kasih

**Comment by Xaxxis** [comment]
Hai @sorryjack pastikan landing page dapat menerima http POST. Midtrans tidak menggunakan session pada saat mengarahkan ke alamat finish redirect url. Untuk best practicenya silahkan mengikuti panduan pada halaman dokumentasi kami. https://docs.midtrans.com/en/core-api/direct-debit?id=_3-create-landing-page-after-customer-complete-the-payment

Untuk pertanyaan spesifik silahkan tanyakan via email support@midtrans.com

Terima kasih
