### ISSUE TITLE
Sample client and server key

### ISSUE THREAD

**Issue by adedayomatt** [Midtrans/midtrans-php#37]
Hello, I'm currently integrating Midrans payment for users in Indonesia using the core API but I can't get client and server keys because I'm not in that region and I could not get an indonesian phone number to register a Midrans account.

Are there sample client and server keys just for testing purpose? If there are, I would appreciate if they can be shared with me. Thanks.

**Comment by Xaxxis** [comment]
Hi @adedayomatt Thank you for reaching out to us. 

For testing purpose you can register by email and use a random phone number, you can register the account [here](https://account.midtrans.com/register). If you have any general question, may you can ask our support team via email at support@midtrans.com 

Thank you
