### ISSUE TITLE
Gopay deeplink fail to open in native Android webview `net::ERR_UNKNOWN_URL_SCHEME` (non PHP specific issue)

### ISSUE THREAD

**Issue by cierish** [Midtrans/midtrans-php#39]
Hi,

We got this error in production mode:

E/onReceivedError: failingUrl=gojek://gopay/merchanttransfer?tref=0120201217034811O35QTUK1ElID&amount=20000&activity=GP:RR&callback_url=https%3A%2F%2Fxxx.com%3Forder_id%3D1-39-95927, errorCode=-10, description=net::ERR_UNKNOWN_URL_SCHEME

The error occurs on Android's webview, although this following code's already added:
`if (url.contains("gojek://")) {
                    Intent intent;
                    intent = new Intent(Intent.ACTION_VIEW);
                    intent.setData(Uri.parse(url));
                    startActivity(intent);
                    return true;
}`

Do you have any suggestion, what could be wrong here?

Thanks,
Cherry

**Comment by rizdaprasetya** [comment]
Hi @cierish 

Very likely it was getting `ERR_UNKNOWN_URL_SCHEME` because the Gojek app is not installed on the device. Commonly happen if you are on simulated/testing device, please make sure to install and login to Gojek app first. Alternatively have someone with real device with installed Gojek app to test it. The URL Scheme is an app deeplink, which requires the app (Gojek) to be installed.

Note: some tips on detecting if an app is installed, when redirecting to an app deeplink:  https://stackoverflow.com/a/41693364

Another possibility if the Gojek app already installed, is somehow the device's OS blocks your app from accessing/redirecting to another installed app. Try testing with another device or non-simulated device first to make sure it works on other device.

Hope it helps. Thanks

**Comment by cierish** [comment]
Hi @rizdaprasetya 

I tested it on real devices where Gojek app already installed and logged in, but it doesn't work either. It seems the URL is still not recognized. I also tried different webview, but it also doesn't work, even though another url like whatsapp: works.

Adding another coding to prove if app installed or not, doesn't make any differences either.

Do you have any other suggestion and solution?

Many thanks

**Comment by rizdaprasetya** [comment]
@cierish Hmm that's strange. Do you use native Android for the webview? or do you use any kind of non-native framework like React Native, Cordova, etc? Those framework might need further config to allow opening deeplink to Gojek app.

Most of the time it solved by following these, please try:
https://midtrans-advanced-faq.netlify.app/#/faq-general?id=customer-fail-to-be-redirected-to-gojek-deeplink-on-mobile-app-what-to-do

Thanks

**Comment by cierish** [comment]
Hi @rizdaprasetya 

Yes, I use native Android and already set and tried different combination for the webview. 
The link you provide has been implemented by us, before the API's activated. 

Is the link gojek:// still available for Android?

Many thanks.

Cheers

**Comment by rizdaprasetya** [comment]
hi @cierish `gojek://` should still be available for Android. I just tried it myself and it still working fine.

Can you open this link on the target device: https://tiny.cc/gj-deeplink-test
Try via external browser (Chrome Android), 
and then via an App called `Webview Test` (from Playstore),
and then via webview from your app.

On my test via multiple devices, clicking the deeplink on that URL from the target device will all open Gojek app.
If it is opening in Chrome Browser & `Webview Test` App, then the device is good, your app may be blocking which may need to be configured.

Thanks.

**Comment by cierish** [comment]
Hi @rizdaprasetya 

Thank you for your information and helps!
With the link and Webview Test, no problem occured.

I'm trying a workaround, not using the webview, and I think it's working now.
I'll do further test.

Many thanks for your helps!

Cheers

**Comment by rizdaprasetya** [comment]
Good to hear you are able to make it work 👍 
If you think you have important findings on the issue/solution, feel free to let us know. So Midtrans/Gojek can take it as feedback, also might be helpful for someone else that may encounter similar issue.

Gojek team is also in progress to improve their Deeplink compatibility by migrating into `Universal Link`, but it may take a while to be fully rolled out, since they need to consider on how to  best handle backward compatibility with existing Deeplink implementation used by various merchants.

Thanks.

**Comment by didaputraa** [comment]
Error for android 11  function shouldOverrideUrlLoading

**Comment by rizdaprasetya** [comment]
Hi @didaputraa yes the method is deprecated, here is updated sample of how to handle for future Android API level:
```java
@SuppressWarnings("deprecation")
@Override
public boolean shouldOverrideUrlLoading(WebView view, String url) {
    final Uri uri = Uri.parse(url);
    return handleWebviewCustomUri(uri);
}
// Include above override only if you need backward-compatibility with Android API level <24
// If you only build for Android API level >=24, start from line below

@TargetApi(Build.VERSION_CODES.N)
@Override
public boolean shouldOverrideUrlLoading(WebView view, WebResourceRequest request) {
    final Uri uri = request.getUrl();
    return handleWebviewCustomUri(uri);
}

private boolean handleWebviewCustomUri(final Uri uri) {
    final String url = uri.toString();
    
    // allow these specified deeplinks to be handled by OS
    if (url.contains("gojek://") || url.contains("shopeeid://")) {
        final Intent intent = new Intent(Intent.ACTION_VIEW, uri);
        startActivity(intent);
        // `true` means for the specified url, will be handled by OS by starting Intent
        return true;
    } else {
        // `false` means any other url will be loaded normally by the WebView
        return false;
    }
}
```

Let us know if you still have any issue. Thanks

**Comment by didaputraa** [comment]
this fiture not work for android 11

Pada Senin, 26 April 2021, Rizda Dwi Prasetya ***@***.***>
menulis:

**Comment by rizdaprasetya** [comment]
@didaputraa can you elaborate what doesn't work? Did you try to implement it?

this is deprecated:
```
shouldOverrideUrlLoading(WebView view, String url)
``` 

but then it is replaced with currently working/supported 
```
shouldOverrideUrlLoading(WebView view, WebResourceRequest request)
```
As [officially documented on Android.com](https://developer.android.com/reference/android/webkit/WebViewClient.html?hl=es#shouldOverrideUrlLoading(android.webkit.WebView,%20android.webkit.WebResourceRequest))

**Comment by didaputraa** [comment]
i have used these 2 functions and the results are the same

do i need, send my application ?

Pada Senin, 26 April 2021, Rizda Dwi Prasetya
***@***.***> menulis:

@didaputraa <https://github.com/didaputraa> can you elaborate what doesn't

**Comment by rizdaprasetya** [comment]
@didaputraa I don't think someone else will be able to debug your application for you, people can only give you suggestion based on commonly known issue. 

You should clarify on the issue you are having. Please share screenshot or error messages of the issue you faced, after following previous comment suggestion.
