### ISSUE TITLE
Recurring response 400

### ISSUE THREAD

**Issue by franschaniago** [Midtrans/midtrans-php#40]
Halo, saya sedang mencoba fitur recurring nya, saya test via api hasil response nya berhasil sesuai dokumentasi recurring tapi kenapa di history sandbox tidak ada ya ?

 kemudian ketika di implementasikan dengan json yang sama, selalu mendapat error response 400

` $params = array(
"name" => "SUBSCRIBE1",
                "amount" => "14000",
                "currency" => "IDR",
                "payment_type" => "credit_card",
                "token" => $request->token_id,
                "schedule"=> array(
                  "interval"=> 1,
                  "interval_unit"=> "month"
                ),
            );
 $response = \Midtrans\CoreApi::charge($params);`

Midtrans Error (400): One or more parameters in the payload is invalid.. Validation Messages (transaction_details is required, credit_card is required)

padahal di dokumentasi transaction_details & credit_card ini tidak ada https://api-docs.midtrans.com/#create-subscription

**Comment by Xaxxis** [comment]
Hi @franschaniago error tersebut muncul dikarenakan API yang digunakan belum tersedia pada library php Midtrans, dikarenakan subscription kami belum dapat digunakan secara umum, jika memang akan digunakan pada environment production silahkan mengubungi sales representative kami. Alternative lain yang bisa digunakan sebagai recurring adalah menggunakan fitur Snap recurring and dapat melihat detailnya pada halaman dokumentasi dibawah ini.
https://docs.midtrans.com/en/snap/advanced-feature?id=recurring-subscription-card-transaction

Untuk pertanyaan umum lainnya silahkan menghubungi tim Support kami melalui email support@midtrans.com

Terima kasih
