### ISSUE TITLE
implementasi notification handler untuk mengubah status transaksi

### ISSUE THREAD

**Issue by pratama-hub** [Midtrans/midtrans-php#41]
saya baru mempelajari midtrans.saya ingin bertanya bagaimana cara implementasi notification handlernya agar transaksi statusnya dapat berubah ??

**Comment by Xaxxis** [comment]
Hi @pratama-hub untuk handle notification Midtrans php anda dapat melihat [sample controller](https://github.com/Midtrans/midtrans-php/blob/master/examples/notification-handler.php ) berikut. Untuk lebih detailnya secara umum anda dapat mengunjungin halaman dokumentasi kami https://docs.midtrans.com/en/after-payment/http-notification?id=https-notification-webhooks

Anda juga dapat menguji/simulasi implementasi code anda pada localhost dengan menggunakan beberapa tunel tools seperti Ngrok, Localtunnel, Serveo, Teleconsole, Pagekite

Semoga membantu, terima kasih
