### ISSUE TITLE
Redirection status code 301, 302 and 303 are not supported. Use 307 or 308 instead.

### ISSUE THREAD

**Issue by andes2912** [Midtrans/midtrans-php#42]
Halo, saya mendapatkan masalah ketika akan menghandle callback notification pada framework Laravel v.8*. 
Terima kasih

**Comment by Xaxxis** [comment]
Hi @andes2912  hal tersebut dikarenakan adanya redirect pada saat Midtrans mengirimkan notifikasi. Pastikan kembali tidak ada redirection pada endpoint notifikasi Anda. Seringkali, hal tersebut terjadi ketika merchant mengisi nilai endpoint notifikasi pada dashboard Midtrans menggunakan protokol http. Namun pada saat Midtrans mengirimkan notifikasi, backend merchant mengarahkan ke https.

Untuk pertanyaan umum lainnya, anda dapat menghubungi kami melalui email ke support@midtrans.com

Semoga membantu, Terima kasih

**Comment by andes2912** [comment]
Hai @Xaxxis, terima kasih sudah meluangkan waktunya, saya sudah cek dan untuk redirection pada dashborad Midtrans sudah sesuai menggunakan protokol HTTPS. 
Terima Kasih

**Comment by Xaxxis** [comment]
Pastikan kembali pada sisi server Anda, untuk tidak melakukan redirect pada endpoint notification. Anda bisa juga melakukan test melalui CURL dengan endpoint notifikasi Anda serta body request yang didapatkan dari history notification Midtrans
```
curl --request POST \
    --url https://YOUR-NOTIF-ENDPOINT \
    --header 'accept: application/json' \
    --header 'content-type: application/json' \
    --data '{
//Replace with JSON notif body request
}' -vvv
```

Untuk pertanyaan umum lainnya, anda dapat menghubungi kami melalui email ke support@midtrans.com dengan melampirkan informasi merchant-id Midtrans yang digunakan.

Terima kasih

**Comment by andes2912** [comment]
@Xaxxis saya menggunakan sedikit perbedaan untuk code nya, bisa lihat [disini](https://gist.github.com/andes2912/958f52a9212a93f6c5f71d63c4163237). Mohon dikoreksi jika ada yg salah.
Terima kasih

**Comment by Xaxxis** [comment]
Hi @andes2912 terlihat pada code anda terdapat command code, redirect kehalaman `/home` pastikan tidak ada redirect sama sekali pada endpoint notifikasi anda. Anda perlu memastikan controller notification Anda, response dengan http status code ya bukan redirection. Seperti yang saya sudah jelaskan sebelumnya, silahkan test kembali endpoint Anda dengan mengirimkan CURL diatas dan cek kembali response yang didapat melalui curl request. 

Sayangnya kami tidak dapat membantu Anda lebih jauh, dikarenakan hal tersebut berada di environment merchant. Jika anda ingin pengecekan lebih lanjut silahkan provide MID Midtrans dan response curl mealui email kami support@midtrans.com ya

sample code laravel, controller
```
Route::post('/notification', function () {

	// Handle Midtrans notification here

    return Response::json(['status' => 'ok'], 200);
});
```

Terima kasih

**Comment by andes2912** [comment]
Halo @Xaxxis saya sudah menghapus redirect pada code tapi error code 3xx masih muncul.
Terima kasih

**Comment by Xaxxis** [comment]
Hi @andes2912 untuk dapat membantu anda lebih lanjut silahkan provide evidence yang dapat membantu kami dalam pengecekan lebih lanjut. Seperti hasil response CURL pada saat hit API endpoint notifikasi Anda atau full code snippet controller endpoint notifikasi Anda. Anda juga dapat mengirimkan via email ke support@midtrans.com 

Terima kasih

**Comment by andes2912** [comment]
Halo @Xaxxis berikut ini adalah code endpoint notifikasi [here](https://gist.github.com/andes2912/958f52a9212a93f6c5f71d63c4163237), 
untuk error nya sendiri yg tertera pada halaman midtrans -> notifications detail adalah seperti ini "Redirection status code 301, 302 and 303 are not supported. Use 307 or 308 instead."
Terima kasih

**Comment by Xaxxis** [comment]
Hi @andes2912 Untuk lebih mudahnya Anda bisa provide [merchant-id](https://dashboard.sandbox.midtrans.com/settings/config_info) Midtrans yang Anda gunakan dan juga link endpoint notifikasi yang dapat diakses oleh public. Gist code yang Anda provide diatas adalah hanya bagian function dalam handle notifikasi Midtrans, namun yang kami maksud adalah full snippet code [controller](https://github.com/Midtrans/Midtrans-Laravel5/blob/master/app/Http/Controllers/SnapController.php) & [Route](https://github.com/Midtrans/Midtrans-Laravel5/blob/master/app/Http/routes.php) laravel Anda dalam endpoint notifikasi Midtrans, seperti berikut ini. Alternative lainnya adalah, Anda juga dapat mencoba menambahkan sample code berikut pada route laravel Anda, sebagai testing endpoint Midtrans Anda

```
Route::post('/notification', function () {

	// Your code to handle Midtrans notification here

    return Response::json(['status' => 'ok'], 200);
});
```
`Redirection status code 301, 302 and 303 are not supported. Use 307 or 308 instead.` Response berikut adalah response yang didapatkan dari Midtrans dashboard. Mohon provide hasil response yang Anda dapatkan melalui CURL request yang telah kami provide sebelumnya diatas. 

Terima kasih

**Comment by herupurwito** [comment]
[https://github.com/harrypujianto/Veritrans-Laravel5/issues/19](url)
setelah baca komentar disini, ternyata masalah saya karena route nya masuk dalam group 
Route::group(['middleware' => ['auth']], function () {}
seharusnya public, hehe

**Comment by rizdaprasetya** [comment]
Betul, untuk menghindari issue pastikan Notification Handler URL di sisi backend Anda (sebagai penerima HTTP request) untuk di-set sebagai `publicly accessible`, tanpa cek authorization ataupun password. Sesuai info [di docs berikut](https://docs.midtrans.com/en/after-payment/http-notification?id=configuring-http-notifications-on-map).

> Make sure that the Notification URL can be reached from Public Internet. Midtrans cannot send notifications to localhost, URL protected with authorization or password, URL behind VPN, unusual destination port, and so on ...

Thanks.
