### ISSUE TITLE
https://api.sandbox.midtrans.com/v2/[ORDER_ID]/status

### ISSUE THREAD

**Issue by abdil1234** [Midtrans/midtrans-php#44]
get 404 response when i add symbol `#` to order id like : ```order_id -> #123123123123```, but when i remove `#` its working properly

**Comment by rizdaprasetya** [comment]
Hi @abdil1234 that may be expected if you are using unusual character in your order-id, that character may result in invalid URL pattern. Please replace with `transaction_id` or avoid using url-non-friendly character:

> Note: You can also replace `order_id` used in API urls with `transaction_id`, which uniquely generated from Midtrans side and you received as response when creating transaction, and from HTTP Notification. This is useful if your `order_id` contains unusual character (such as `#`) that may result in an invalid URL pattern.

**Comment by abdil1234** [comment]
oke terimakasih
