### ISSUE TITLE
how to check snap token is no longer valid?

### ISSUE THREAD

**Issue by abdil1234** [Midtrans/midtrans-php#46]

**Comment by rizdaprasetya** [comment]
Hi @abdil1234 this information is explained on this section:
https://docs.midtrans.com/en/snap/advanced-feature?id=snap-token-expiry-time

> The default lifetime for regular Snap transaction, Snap token and also the redirect_url, is 24 hours. It can be customized. To customize Snap token and redirect_url, refer to [Custom Expiry](https://docs.midtrans.com/en/snap/advanced-feature?id=custom-transaction-expiry) section.

Thanks

**Comment by rizdaprasetya** [comment]
Closing the issue due to inactivity, please reply or contact Midtrans Support email if you have any further questions. Thanks!
