### ISSUE TITLE
Saya tidak menemukan endpoint untuk mendapatkan seluruh data invoice

### ISSUE THREAD

**Issue by muh-hizbe** [Midtrans/midtrans-php#47]
Hallo, bisakah kita mendapatkan seluruh data transaksi yang dibuat?

Seperti halnya yang terdapat di https://dashboard.sandbox.midtrans.com/transactions yang menampilkan seluruh data transaksi.

**Comment by Xaxxis** [comment]
Hi @muh-hizbe untuk menarik data transaksi yang ada di halaman transactions dashboard Midtrans, Anda dapat mendownloadnya langsung melalui menu transactions. Berikut ini adalah dokumentasi yang dapat anda jadikan panduan
https://docs.midtrans.com/en/after-payment/dashboard-usage?id=sending-transaction-report-to-email

Jika yang Anda maksud adalah API untuk menarik data transaksi yang telah Anda buat sebelumnya, sayangnya saat ini API tersebut belum tersedia. Namun untuk mendapatkan status tiap transaksi Anda, Anda dapat menggunakan API Get Status
https://docs.midtrans.com/en/after-payment/get-status?id=get-status-api-requests

Untuk pertanyaan umum lainnya, silahkan menghubungi kami via email support@midtrans.com
Terima kasih

**Comment by muh-hizbe** [comment]
Baik terimakasih
