### ISSUE TITLE
Can snap token re-used to open payment page again, if it was closed by customer?

### ISSUE THREAD

**Issue by PandhuWibowo** [Midtrans/midtrans-php#49]
Hi guys, I have problem in Credit Card Transaction. The important part is in token page after user / buyer / customer input the CC number etc, the next part is should input the token (OTP), but I want to cancel this moment, and then I want to checkout for the twice, unfortunately the snap does not show anymore. How could I fix it? Please explain this problem guys,

The case : 
[https://drive.google.com/file/d/1_pDxVEzWzUdU1VJj8ByHj2gh95R2iOsF/view?usp=sharing](https://drive.google.com/file/d/1_pDxVEzWzUdU1VJj8ByHj2gh95R2iOsF/view?usp=sharing)

I already followed this guide, but still does not work.
<img width="800" alt="Screen Shot 2021-07-08 at 17 22 24" src="https://user-images.githubusercontent.com/22772782/124906260-123d3880-e011-11eb-97c5-f07949c64360.png">

Reference : 
[https://docs.midtrans.com/en/other/faq/technical?id=can-i-revoke-or-cancel-an-active-snap-token-to-prevent-the-customer-from-proceeding-with-the-transaction](https://docs.midtrans.com/en/other/faq/technical?id=can-i-revoke-or-cancel-an-active-snap-token-to-prevent-the-customer-from-proceeding-with-the-transaction)

please contact me on pandhu@antikode.com or 081387019695 to reply this issue or ask the details.
 thanks in advance.

**Comment by mjamilasfihani** [comment]
I think, this is a simple problem that peoples like you can fix it.

**Comment by PandhuWibowo** [comment]
Really? I have no idea. I think this condition officially from this package. Can you help me what should I do?

**Comment by PandhuWibowo** [comment]
i think I found the problem, midtrans can receive similar the order_id? 

I got feedback, that I have been sent the order_id
<img width="586" alt="Screen Shot 2021-07-09 at 10 25 11" src="https://user-images.githubusercontent.com/22772782/125018767-f3d24e00-e09f-11eb-83c7-e88e6cbb5b31.png">

**Comment by rizdaprasetya** [comment]
Hi @PandhuWibowo thanks for reaching us!
So if I understand correctly, the question is:
- How to re-open that same Snap payment page, if it was closed by user?

The answer is:
1. Store the `Snap Token` for that order
2. On Frontend call `snap.pay('that-snap-token');` again when your web/app want to re-open that same payment page for that order

We also just added a new section explaining about this use case here:
- https://docs.midtrans.com/en/snap/advanced-feature?id=allowing-customer-to-re-pay-the-same-order

Let us know if you still have more questions, or if we misunderstood your question, feel free to re-explain (you can also use Bahasa Indonesia if needed).

For better & faster response you can also contact us via email support@midtrans.com
Thank you! 🙂

**Comment by PandhuWibowo** [comment]
Many thanks, I have given the random string at the last order id to re-create snap token. The case can be closed.
