### ISSUE TITLE
Mendapatkan attribute actions pada endpoint /charge

### ISSUE THREAD

**Issue by Firman95** [Midtrans/midtrans-php#50]
Di Core API, response dari `/charge` bisa dapat attribute `actions` jika menggunakan qris/gopay. Apakah ada cara lain untuk mendapatkan isi dari attribute `actions` selain dari `/charge`?

**Comment by Xaxxis** [comment]
Hi @Firman95 untuk mendapatkan property `action`, pada payment type gopay. Betul, Anda hanya bisa dapatkan setelah berhasil melakukan API `/charege`.  Agar jawaban yang kami berikan bisa lebih tepat, mungkin bisa dijelaskan lebih spesifik kebutuhannya  yang diinginkan seperti apa?

Docs references: https://docs.midtrans.com/en/core-api/e-wallet

Untuk pertanyaan umum lainnya, silahkan menghubungi kami via email support@midtrans.com

Terima kasih

**Comment by Firman95** [comment]
Kebutuhannnya untuk dapat memunculkan kembali qr code atau deep link ke app gopay tanpa harus menyimpan url-url tersebut. Berarti memang tidak bisa ya, harus disimpan urlnya.
