### ISSUE TITLE
Apakah bisa menonaktifkan redirect ke Finish URL?

### ISSUE THREAD

**Issue by adeindriawan** [Midtrans/midtrans-php#51]
Saya sedang mengintegrasikan Snap Midtrans ke dalam aplikasi saya dengan Laravel sebagai _backend_, dan React sebagai _frontend_. Aplikasi tersebut berkonsep _single page app_ (SPA) sehingga perpindahan antar halaman di-_handle_ oleh `react-router`/`react-router-dom` tanpa proses _reload_/_refresh_/_redirect_ halaman web.

Saat ini saya sedang menambahkan fitur Snap di aplikasi tersebut, namun sedang mengalami kesulitan karena tiap kali _user_ selesai memilih metode pembayaran, Snap akan me-_redirect_ aplikasi ke URL yang sudah ditentukan di Midtrans Dashboard. Proses _redirect_ tersebut membuat _state_ aplikasi saya menjadi terganggu. Padahal, saya sudah menggunakan JS _callbacks_, khususnya pada opsi onPending. Sebagaimana yang tertulis di dokumentasi,

> If Merchant use snap.js JS callbacks (onPending, onSuccess, onError), those JS callbacks will be triggered instead of redirection.

Saya sudah mencoba menghapus Finish URL di _dashboard_ maupun _override_ Finish URL melalui _backend_, namun hasilnya Snap akan terus me-_redirect_ (kali ini ke halaman utama _frontend_ aplikasi saya). Saya juga sudah lihat dokumentasi, dan sepertinya tidak ada opsi untuk menonaktifkan fitur _redirect_ ke Finish URL tersebut.

Mohon arahannya, terima kasih.

**Comment by Xaxxis** [comment]
Hi @adeindriawan
Jika anda membuka halam snap melalui Snap.JS maka secara default tidak akan melakukan redirect. Akan sangat sulit jika tanpa melihat sample code anda. Pada dasarnya library snap.js tidak spesifik di design untuk ReactJS. Tapi in theory, selama ReactJS berjalan di frontend dan implementasi Anda sudah sesuai, seharusnya bisa digunakan bersamaan dengan snap.js.

Untuk details terkait Snap.JS anda dapat melihat pada halaman dokumentasi berikut https://snap-docs.midtrans.com/#snap-js
[Discussion terkait implementasi Snap.JS dengan reacJS](https://github.com/Midtrans/midtrans-nodejs-client/issues/5)

Terima kasih

**Comment by Xaxxis** [comment]
Hi @adeindriawan Menambahkan   penjelasan diatas, Anda bisa make sure kembali untuk payment method yang digunakan, beberapa payment-method seperti direct-debit, cardless credit seperti akulaku expected saat melakukan pembayaran, memang akan diarahkan (redirect) ke halaman payment provider (bank) dan setelah customer berhasil bayar, akan diarahkan Finish redirect-url.

Terima kasih

**Comment by Xaxxis** [comment]
No response from the author, If you have any general questions, please contact us via email support@midtrans.com

Thank you

**Comment by zukhrofy** [comment]
cukup kasih callback aja di frontend nya @adeindriawan. kebetulan saya pakai vue.
`window.snap.pay(res.snap_token, {
                    onSuccess: function (result) {
                        messageResponse.value =
                            "Berhasil melakukan transaksi, Silahkan Tunggu Konfirmasi Dari Kami";
                    },
                    onPending: function (result) {
                        messageResponse.value =
                            "Pembayaran Anda sedang diproses. Mohon selesaikan pembayaran segera.";
                    },
                    onError: function (result) {
                        errorValue.value =
                            "Maaf, terjadi kesalahan. Silakan coba lagi";
                    },
                    onClose: function () {
                        errorValue.value =
                            "you closed the popup without finishing the payment";
                    },
                }); 
`
kalau kita nyediakan callback di pemanggilan snap di frontend, maka midtrans gak akan redirect ke finish_url

**Comment by rakafebriansy** [comment]
> cukup kasih callback aja di frontend nya @adeindriawan. kebetulan saya pakai vue. `window.snap.pay(res.snap_token, { onSuccess: function (result) { messageResponse.value = "Berhasil melakukan transaksi, Silahkan Tunggu Konfirmasi Dari Kami"; }, onPending: function (result) { messageResponse.value = "Pembayaran Anda sedang diproses. Mohon selesaikan pembayaran segera."; }, onError: function (result) { errorValue.value = "Maaf, terjadi kesalahan. Silakan coba lagi"; }, onClose: function () { errorValue.value = "you closed the popup without finishing the payment"; }, }); ` kalau kita nyediakan callback di pemanggilan snap di frontend, maka midtrans gak akan redirect ke finish_url

Gaguna jir, masih aja ke-redirect ke http://localhost:5173/product/1?order_id=6&status_code=200&transaction_status=settlement

**Comment by stievenk** [comment]
Saya juga mengalami masalah yang sama, berikut trik yang saya gunakan
Pertama atur finish_url di Dashboard Snap Preference Midtrans, kosong URL nya. (Optional: kosongkan juga Unfinish & Error URL)

Selanjutnya tambahkan paramater **callbacks => 'javascript:void(0)'** di request body pada saat create snap_token
(https://docs.midtrans.com/reference/request-body-json-parameter)

Sample Code
`$transaction = array(
            'enabled_payments' => $enable_payments,
            'transaction_details' => $transaction_details,
            'customer_details' => $customer_details,
            'item_details' => $item_details,
            "callbacks" => array(
                            'finish' => 'javascript:void(0)',
                            )`

**Comment by SaefulA0** [comment]
@rakafebriansy owkowkwowk sama njir
