### ISSUE TITLE
Midtrans snap token

### ISSUE THREAD

**Issue by wafik** [Midtrans/midtrans-php#55]
Ketika menggunakan snap token, dengan metode pembayaran shopeepay dan gopay, Qris, bagai mana mendapatkan qr code seperti  saat menggunakan coreapi. 

         "transaction_time": "2019-10-08 12:41:36",
	  "transaction_status": "pending",
	  "fraud_status": "accept",
	  "actions": [
	      {
	        "name": "generate-qr-code",
	        "method": "GET",
	        "url": "https://api.sandbox.veritrans.co.id/v2/gopay/231c79c5-e39e-4993-86da-cadcaee56c1d/qr-code"
	      },
	      {
	        "name": "deeplink-redirect",
	        "method": "GET",
	        "url": "https://simulator.sandbox.midtrans.com/gopay/ui/checkout?referenceid=Y0xwjoQ9uy&callback_url=someapps%3A%2F%2Fcallback%3Forder_id%3Dorder-101h-1570513296"
	      },
	      {
	        "name": "get-status",
	        "method": "GET",
	        "url": "https://api.sandbox.veritrans.co.id/v2/231c79c5-e39e-4993-86da-cadcaee56c1d/status"
	      },
	      {
	        "name": "cancel",
	        "method": "POST",
	        "url": "https://api.sandbox.veritrans.co.id/v2/231c79c5-e39e-4993-86da-cadcaee56c1d/cancel"
	      }
	  ]

**Comment by Andrenzo17** [comment]
Hi @wafik 

Snap adalah hosted payment page yang di-design dengan tujuan agar merchant dapat implementasi dengan aman dan mudah dan Core API sendiri di-design lebih advanced agar merchant dapat melakukan implementasi sesuai dengan kebutuhan bisnis yang Anda inginkan. Sayangnya untuk saat ini Snap tidak memiliki fitur, untuk mendapatkan reponse QRCode secara langsung melalui API. Fitur tersebut hanya tersedia pada Core-API.

Terima kasih
