### ISSUE TITLE
How to set Dynamic payment notification ?

### ISSUE THREAD

**Issue by hermans** [Midtrans/midtrans-php#59]
Bagimana untuk melakukan dynamic notification lewat code PHP, sebelumnya saya menggunakan kode ini:

~~~
 \Veritrans_Config::$curlOptions[CURLOPT_HTTPHEADER] = array(
             'X-Override-Notification: https:/www.test/notication'
        );
~~~

tapi sekarang ngak jalan

![image](https://user-images.githubusercontent.com/938767/133064823-a9588df9-89dd-490d-af70-7a581ddc7746.png)

**Comment by Andrenzo17** [comment]
Hi @hermans bisa tolong pastikan kembali untuk implementasinya sudah sesuai atau belum melalui backend?

**Comment by Andrenzo17** [comment]
hi @hermans bisa tolong di pastikan kembali apakah implementasinya sudah sesuai atau belum?
https://github.com/Midtrans/midtrans-php#override-notification-url

// Use new notification url(s) disregarding the settings on Midtrans Dashboard Portal (MAP)
Config::$overrideNotifUrl = "https://example.com/test1";

Bisa diinfokan juga menggunakan library Midtrans versi berapa? Thank you

**Comment by hermans** [comment]
ok sya baru lihat kalau ada method baru, akan saya coba implementasikan. 
saya pakai versi:
>  "veritrans/veritrans-php": "dev-master",

**Comment by hermans** [comment]
Apakah masih bisa saya gunakan yang versi lama (veritrans/veritrans-php), jika tidak berarti saya mesti update code program yang sudah saya buat beberapa tahun lalu

**Comment by Andrenzo17** [comment]
Saat ini untuk veritrans PHP sudah tidak di update, saya sarankan untuk menggunakan versi terbaru dari Midtrans PHP ya.

**Comment by hermans** [comment]
Saya sudah coba upgrade ke versi baru tapi masih tetap sama errornya, code baru untuk overide url notification:

~~~
// Set your Merchant Server Key
        \Midtrans\Config::$serverKey = $this->server_key;
        // Set to Development/Sandbox Environment (default). Set to true for Production Environment (accept real transaction).
        \Midtrans\Config::$isProduction =  $this->production;
        // Set sanitization on (default)
        \Midtrans\Config::$isSanitized = $this->sanitized;
        // Set 3DS transaction for credit card to true
        \Midtrans\Config::$is3ds = $this->_3DS;

        $url = Yii::app()->createAbsoluteUrl('ajax/paymentnotify',[
            'code'  => 'midtrans'
        ]);

        \Midtrans\Config::$appendNotifUrl = $url;
        \Midtrans\Config::$overrideNotifUrl = $url;
~~~

**Comment by Andrenzo17** [comment]
Saya baru saja mencoba menggunakan midtrans PHP v2.5.2
Untuk override url berjalan dengan baik

`Config::$overrideNotifUrl = "https://example.com";`

**Comment by Andrenzo17** [comment]
hi @hermans bisa tolong jelaskan lebih detail maksud dari error-nya bagaimana? serta tolong lampirkan evidance yang dimaksud agar saya bisa cek.

Terima kasih

**Comment by hermans** [comment]
maaf error di internal code saya, jadi error ditas itu bukan masalah notification, tapi karena saya tidak ada method "pending" jadi mitrans manggil default value, Saya masih pelajari lebih lenjut
~~~
onPending: function(result){
            <?php
              echo $pending_html;
            ?>
          },
~~~
