### ISSUE TITLE
 array_key_exists is deprecated in PHP 7.4

### ISSUE THREAD

**Issue by andrewklau** [Midtrans/midtrans-php#6]
array_key_exists() is deprecated in PHP 7.4

```
array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead {"exception":"[object] (ErrorException(code: 0): array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead at /app/vendor/midtrans/midtrans-php/Midtrans/Notification.php:32)
```

**Comment by rizdaprasetya** [comment]
Hi @andrewklau thanks for the catch.

But currently PHP 7.4 have not made it to the official release yet:
https://www.php.net/releases/index.php

And according to the official doc, there were no deprecation of  `array_key_exists` yet
https://www.php.net/manual/en/function.array-key-exists.php

So for now it's not high priority, but we'll take a look to prepare for future PHP 7.4 release.

Thanks!

**Comment by rizdaprasetya** [comment]
Edit: Oh wait sorry, my bad. It was wrong reference. Yes it was official few weeks ago.
https://www.php.net/downloads.php
So yes, it will be high priority to update. We'll check. Thanks for the catch!

**Comment by rizdaprasetya** [comment]
Should be closed by https://github.com/Midtrans/midtrans-php/pull/9 just now

**Comment by reapera** [comment]
@rizdaprasetya still have array_key_exists on v2.3.0 please help ya 
https://github.com/Midtrans/midtrans-php/blob/v2.3.0/Midtrans/Snap.php#L65
