### ISSUE TITLE
Sandbox GoPay Payment failure

### ISSUE THREAD

**Issue by hermans** [Midtrans/midtrans-php#60]
Beberapa kali melakukan test dengan gopay, ada pilihan dropdown "success" > "pay" tapi habis itu selalu error seperti ini:

![image](https://user-images.githubusercontent.com/938767/133735653-f1b2b650-3eb0-4a5f-add0-13f41159e53c.png)

sebelumnya saya copy QR Code url dan saya pasti di inputbox, kira2 kenapa error ini ya ?

**Comment by omarxp** [comment]
Hi @hermans 
silakan gunakan simulator qris untuk pembayaran:
https://simulator.sandbox.midtrans.com/qris/index

jika masih eror, silakan informasikan order-id yang sedang ditest, akan kami cek lebih lanjut, terima kasih.

**Comment by hermans** [comment]
pakai qris malah error, pas press button.

order-id: 11002109616308

**Comment by omarxp** [comment]
baik, akan kami cek terlebih dahulu
