### ISSUE TITLE
404 Not Found Transaction

### ISSUE THREAD

**Issue by hogivano** [Midtrans/midtrans-php#61]
Hi, I have some issues with the status transactions. Here my response "Midtrans API is returning API error. HTTP status code: 404 API response: { "status_code": "404", "status_message": "Transaction doesn't exist.", "id": "4e64ffc3-f937-4345-a7d4-6638593d560a"}". I'm trying using sandbox API v2 and my order is HEND-1829. If I check back to redirect_url it's working as well but if I check status API the response is 404 not found. Thank You

**Comment by Andrenzo17** [comment]
Hi @hogivano i already check this order id HEND-1829 or this transaction 4e64ffc3-f937-4345-a7d4-6638593d560a not found in Midtrans. 

Please confirm again, that order id already send to Midtrans.

Thank you

**Comment by hogivano** [comment]
That's my example, for the real case is order id = BWA-41675 this transaction is 5e5129ca-55d2-4b3d-a64e-962214463ac6

Thank You

**Comment by Andrenzo17** [comment]
i'm still cannot find this order id = BWA-41675 and this transaction c86c9cc9-11fb-4c81-ae65-11310f774e9b in sandbox.

You need to make sure the order id have success to create. If the order id already show in Midtrans dashboard https://dashboard.sandbox.midtrans.com/transactions you can try check transaction status again.

If the order id not show in Midtrans dashboard and you try check transactions status. it's expected get "status_message": "Transaction doesn't exist.

thanks

**Comment by hogivano** [comment]
Okay, I'll check it, thank you for your help.
