### ISSUE TITLE
midtrans Error Notification

### ISSUE THREAD

**Issue by farhan048** [Midtrans/midtrans-php#63]
Order ID:
Shuttle-61a7aeb5647f7

Current endpoint:
https://shuttlein.online/api/midtrans/notification

Content-Type:
application/json

Notification data:
{
  "va_numbers": [
    {
      "va_number": "69246547150",
      "bank": "bca"
    }
  ],
  "transaction_time": "2021-12-02 00:19:54",
  "transaction_status": "settlement",
  "transaction_id": "d2480bac-9371-4bc1-a941-0b9af9c7a218",
  "status_message": "midtrans payment notification",
  "status_code": "200",
  "signature_key": "6b9eefbe7f5f561672f5bd36d058da241db98e9adaf7a704856258fc36ff539d2d4f390b142c8ca823a8131e6e67cf90bda941e0ac2d9bd3dabc83d3dbd8fc62",
  "settlement_time": "2021-12-02 00:20:04",
  "payment_type": "bank_transfer",
  "payment_amounts": [],
  "order_id": "Shuttle-61a7aeb5647f7",
  "merchant_id": "G064569246",
  "gross_amount": "145000.00",
  "fraud_status": "accept",
  "currency": "IDR"
}
Error detail:
InternalServerError

Transaction Page:
https://dashboard.sandbox.midtrans.com/payments/d2480bac-9371-4bc1-a941-0b9af9c7a218

adakah solusi untuk error yang saya alami ?

**Comment by rizdaprasetya** [comment]
Hi @farhan048 hopefully issuenya sudah solved karena sudah di close. Tapi kalau berlanjut: 
Kelihatannya issuenya adalah backend Anda menolak HTTP POST webhook/notiification dari Midtrans. Jadi yg perlu di fix adalah dari sisi backend Anda sebagai penerima. Silahkan bisa mengikuti FAQ berikut ya:
- https://docs.midtrans.com/en/other/faq/technical?id=how-to-troubleshoot-http-notification-failures
Thanks.
