### ISSUE TITLE
enable_payments tetep tampill semua payment channel

### ISSUE THREAD

**Issue by hermans** [Midtrans/midtrans-php#65]
Halo, saya lagi coba fitur enable_payment untuk 1 pembayaran saja "gopay" snap, tapi ketika popup window teteap tampil semua, saya ikutin cara ini:
~~~
{
  "transaction_details": {
    "order_id": "ORDER-101",
    "gross_amount": 10000
  },
  "item_details": [{
    "id": "ITEM1",
    "price": 10000,
    "quantity": 1,
    "name": "Midtrans Bear",
    "brand": "Midtrans",
    "category": "Toys",
    "merchant_name": "Midtrans"
  }],
  "customer_details": {
    "first_name": "TEST",
    "last_name": "MIDTRANSER",
    "email": "test@midtrans.com",
    "phone": "+628123456"
  },
  "enabled_payments": ["gopay"],
  "gopay": {
    "enable_callback": true,
    "callback_url": "http://gopay.com"
  }
}
~~~

mestinya dia hanya tampil GoPay saja

apa mungkin ada setting yang lain ?

**Comment by Andrenzo17** [comment]
Hi @hermans untuk parameter diatas sudah benar ya dan memang hanya akan tampil payment method Gopay saja.
Boleh infokan merchant id dan sample order id nya, agar bisa kami pastikan untuk parameter yang dikirim ke Midtrans sudah sesuai atau belum.
https://docs.midtrans.com/en/snap/advanced-feature?id=specify-payment-channel

Terima kasih

<img width="1063" alt="Screenshot 2022-02-03 at 14 44 46" src="https://user-images.githubusercontent.com/83454487/152301724-4a061a8b-4d0a-47af-925e-752db6779284.png">
<img width="1305" alt="Screenshot 2022-02-03 at 14 44 59" src="https://user-images.githubusercontent.com/83454487/152301739-44b8cee5-d483-4688-a1a1-5c8f3cc76f6b.png">

**Comment by hermans** [comment]
> G016692287

**Comment by hermans** [comment]
seperti ini format json:
~~~
{"client_key":"SB-Mid-","action":"https:\/\/app.sandbox.midtrans.com\/snap\/snap.js","enabled_payments":["gopay"],"gopay":{"enable_callback":true,"callback_url":"http:\/\/localhost\/labku\/appku\/checkout\/success?order_id=10202202038497"},"transaction_details":{"order_id":10202202038497,"gross_amount":734800},"customer_details":{"first_name":"test","last_name":"testx","email":"test@test.com","phone":"23232","billing_address":{"first_name":"test","last_name":"testx","email":"test@test.com","phone":"23232","address":"tdd","city":"Bangka Barat","postal_code":"23232","country_code":"IDN"},"shipping_address":{"first_name":"test","last_name":"testx","email":"test@test.com","phone":"23232","address":"tdd","city":"Bangka Barat","postal_code":"23232","country_code":"IDN"}},"item_details":[{"id":"B0046-4548654780641","price":0,"quantity":1,"name":"Kuruku Beige - 2Pcs - (Sepasang) 100 cm (lebar) x 135 cm (panjang)"},{"id":"","price":734800,"quantity":1,"name":"Grand Total"}],"logo":"\/labku\/appku\/assets\/d650ab4c\/logo_midtrans.png","transaction":{"customer_details":{"first_name":"test","last_name":"testx","email":"test@test.com","phone":"23232","billing_address":{"first_name":"test","last_name":"testx","email":"test@test.com","phone":"23232","address":"tdd","city":"Bangka Barat","postal_code":"23232","country_code":"IDN"},"shipping_address":{"first_name":"test","last_name":"testx","email":"test@test.com","phone":"23232","address":"tdd","city":"Bangka Barat","postal_code":"23232","country_code":"IDN"}},"item_details":[{"id":"B0046-4548654780641","price":0,"quantity":1,"name":"Kuruku Beige - 2Pcs - (Sepasang) 100 cm (lebar) x 135 cm (panjang)"},{"id":"","price":734800,"quantity":1,"name":"Grand Total"}],"transaction_details":{"order_id":10202202038497,"gross_amount":734800}}}
~~~

**Comment by Andrenzo17** [comment]
> 

untuk param format json di atas sudah saya coba ya dan hasilnya sudah sesuai akan muncul payment method gopay saja.
Namun saat dikirim terkena validasi item name

{
    "error_messages": [
        "Items Name too long"
    ]
}

Agar requestnya berhasil maka untuk name pada item_details harus dikurangi jumlah hurufnya ya.
Bisa tolong lampirkan screenshot pop up yang menunjukan semua payment method muncul walaupun sudah enabled payment gopay?
Terima kasih

<img width="1303" alt="Screenshot 2022-02-03 at 15 47 45" src="https://user-images.githubusercontent.com/83454487/152309972-85ba4bfc-e8f8-4aa0-ac13-eb5083846678.png">

<img width="1067" alt="Screenshot 2022-02-03 at 15 47 32" src="https://user-images.githubusercontent.com/83454487/152309956-af1b591b-edcb-4779-8c32-b8b5ab1ae4ae.png">

**Comment by hermans** [comment]
ok, akan saya kurangi jumlah huruf di produknya, berapa ya max nya ?

ini contoh tampilan popup paymentnya;
![image](https://user-images.githubusercontent.com/938767/152312330-63253248-d1fa-4623-a5fa-db973cd3f033.png)

**Comment by Andrenzo17** [comment]
Mohon maaf sebelumnya pak @hermans sepertinya sempat ada missing log sandbox pada sisi kami.
Mohon kesediaannya untuk coba kembali dan infokan order id yang terbaru agar saya bisa cek log yang diterima Midtrans ya.

Terima kasih

**Comment by hermans** [comment]
order id:
> 10202202038497

**Comment by Andrenzo17** [comment]
Pak untuk order id `10202202038497` request terakhir sekitar pukul 16.00.
Boleh tolong coba lagi ga pak, buat order id baru yang berbeda dengan order id di atas.
Terima kasih

**Comment by hermans** [comment]
order_id:
> 10202202061020

**Comment by Andrenzo17** [comment]
Pak setelah saya cek pada log untuk order id di 10202202061020 dikirim ke Midtrans pada kemarin hari sekitar pukul 17.13 WIB. kalau di check tidak ada param enabled_payments sehingga expected akan muncul semua pilihan metode pembayaran.

Selain mengatur specify payment channel dari API request, bisa juga dilakukan melalui dashboard midtrans ya berikut caranya https://docs.midtrans.com/en/snap/advanced-feature?id=a-specify-payment-channel-via-dashboard

```
{
	"transaction_details": {
		"order_id": "10202202061020",
		"gross_amount": 759000
	},
	"customer_details": {
		"billing_address": {
			"city": "Tangerang Selatan",
			"phone": "2323223",
			"address": "tes",
			"last_name": "test",
			"country_code": "IDN",
			"postal_code": "222",
			"first_name": "test",
			"email": "test@test.com"
		},
		"phone": "2323223",
		"shipping_address": "[FILTERED]",
		"last_name": "test",
		"first_name": "test",
		"email": "test@test.com"
	},
	"credit_card": {
		"secure": "0"
	},
	"item_details": [{
		"price": 0,
		"name": "Sora to Chicken - 2Pcs - (Sepasang) 100 cm (lebar)",
		"id": "D4177-4548654783345",
		"quantity": 1
	}, {
		"price": 759000,
		"name": "Grand Total",
		"id": "",
		"quantity": 1
	}]
}
"credit_card": {
	"secure": "0"
},
"item_details": [{
	"price": 0,
	"name": "Sora to Chicken - 2Pcs - (Sepasang) 100 cm (lebar)",
	"id": "D4177-4548654783345",
	"quantity": 1
}, {
	"price": 759000,
	"name": "Grand Total",
	"id": "",
	"quantity": 1
}]
}
```

**Comment by hermans** [comment]
ok, akan saya cek lagi
