### ISSUE TITLE
In case anyone looking for alternative package, I made sawirricardo/midtrans-api or sawirricardo/laravel-midtrans

### ISSUE THREAD

**Issue by sawirricardo** [Midtrans/midtrans-php#68]
Hi everyone, I made a package as an alternative for anyone looking for better typed support.
It currently handles snap payment and get transaction status, since these are all I need for now.

If you develop on laravel, I also make a wrapper which you can use.

1. https://github.com/sawirricardo/midtrans-api - `composer require sawirricardo/midtrans-api`
2. https://github.com/sawirricardo/laravel-midtrans - `composer require sawirricardo/laravel-midtrans`

If you have any feedback, PRs and ideas are welcomed. Discussions are also open.
Thank you

**Comment by rizdaprasetya** [comment]
Hi @sawirricardo that's wonderful! 😃 At Midtrans we do love community contribution, moreover from an open source enthusiast & seasoned developer like you.

We'll check your repos and see if we can add the link on our docs site: https://docs.midtrans.com/en/technical-reference/library-plugin?id=language-library (we do have community contribution section to list such things) for better visibility & proper exposure. Will update soon.

Thanks for letting us know & your great contribution 🚀
