### ISSUE TITLE
CURL Error: SSL certificate problem: self signed certificate in certificate chain 

### ISSUE THREAD

**Issue by fakhryhizballah** [Midtrans/midtrans-php#69]
VENDORPATH\midtrans\midtrans-php\Midtrans\ApiRequestor.php at line 138

**Comment by Andrenzo17** [comment]
Hi @fakhryhizballah bisa tolong jelaskan lebih detail maksud dari error-nya bagaimana? serta tolong lampirkan evidance yang dimaksud agar saya bisa cek lebih lanjut.

Terima kasih

**Comment by fakhryhizballah** [comment]
di localhost error
![image](https://user-images.githubusercontent.com/50532299/161484763-298bed85-05a0-4654-94ea-ab07788b1b47.png)

Di prodution token muncul cuma snap tidak terbuka

**Comment by fakhryhizballah** [comment]
![image](https://user-images.githubusercontent.com/50532299/161485001-7411c53f-dff9-45e5-b5d6-530641a2d1e1.png)

**Comment by Andrenzo17** [comment]
Hi, boleh tolong di infokan untuk versi library Midtrans php yang digunakan? Serta infokan juga versi php yang di install di local?

Thanks

**Comment by Andrenzo17** [comment]
Hi @fakhryhizballah saat ini saya sudah coba dengan versi PHP 7.3 dan PHP 7.4 namun tidak mengalami kendala serupa.
Sepertinya untuk setup environment local yang belum sesuai, mungkin bisa coba dulu untuk fix cURL error 60: SSL certificate problem nya

Terima kasih

https://medium.com/@narendravaghela/how-to-fix-curl-error-60-ssl-certificate-problem-80e7dafafa57#:~:text=This%20error%20occurs%20because%20the,certificate%2C%20it%20throws%20an%20error.&text=Open%20your%20php.,or%20update%20the%20following%20line

**Comment by Jangbe** [comment]
Mungkin masalahnya hanya dilokal, karena memakai self-signed certificate (kasus saya dari laragon), coba tambahin code berikut biar tidak diverify, tapi menurut saya ini hanya untuk local saja tidak untuk production

\Midtrans\Config::$curlOptions[CURLOPT_SSL_VERIFYHOST] = 0;
\Midtrans\Config::$curlOptions[CURLOPT_SSL_VERIFYPEER] = 0;
\Midtrans\Config::$curlOptions[CURLOPT_HTTPHEADER] = [];
