### ISSUE TITLE
Gopay QRCode "Unrecognized QR Code"

### ISSUE THREAD

**Issue by hermans** [Midtrans/midtrans-php#70]
Kami memiliki beberapa merchant yang mengguankan Midtrans - Gopay, salah satu merchant error saat coba scan qrcode untuk melakukan pembayaran

![image](https://user-images.githubusercontent.com/938767/161476070-cde80e26-c9fa-45d1-81b0-1192f6d3da82.png)

error saat scan:
![image](https://user-images.githubusercontent.com/938767/161476152-9c22220c-34e1-41fb-bd21-6b1c588060f8.png)

**Comment by Andrenzo17** [comment]
Hi @hermans ini untuk merchant G631404871 Univers Indonesia ya?

Untuk kendala ini akan kami cek lebih lanjut dulu. Mohon untuk menunggu

Terima kasih

**Comment by hermans** [comment]
iya betul

**Comment by Andrenzo17** [comment]
Hi @hermans jika di cek lebih lanjut untuk merchant ini belum menyelesaikan pendaftaran untuk QRIS Gopay activation sehingga expected mendapatkan response diatas. Silakan selesaikan proses aktivasinya terlebih dahulu.

Karena open issue tapi bukan related soal library/pluginsnya. saya arahkan untuk ke https://midtrans.com/id/contact-us/technical-integration-development/other-question karena github ini public menghindari informasi yg kurang relevan bisa diakses oleh public.

Terima kasih

**Comment by hermans** [comment]
Ok, bisa di remove aja issue ini ?
