### ISSUE TITLE
No payment channels available

### ISSUE THREAD

**Issue by galangbuana26** [Midtrans/midtrans-php#71]
![midtrans-screenshot](https://user-images.githubusercontent.com/66818849/165014115-e4ae3979-7cf3-489c-8337-1afa9902cf67.png)
Payment channel tidak tersedia saat saya menggunakan snap. Hal ini juga terjadi pada saat saya ingin membuat payment link, saat ingin memilih metode pembayaran tertulis No payment method available. Saya sudah mencoba mendaftarkan akun baru namun sama saja, saya juga sudah menghubungi help center namun belum ada solusi.

Mohon bantuannya, terimakasih.

**Comment by Andrenzo17** [comment]
Hi @galangbuana26 

Karena issuenya bersifat account-specific, untuk penyelesaian yang lebih personal & menjaga keamanan/privasi akun Anda, kami sarankan untuk melanjutkan menghubungi kami secara direct message melalui jalur kontak berikut: https://midtrans.com/id/contact-us/technical-integration-development/other-question

Jika sudah menghubungi help center namun belum ada jawaban, boleh tolong infokan email yang digunakan untuk pelaporannya?

Terima kasih
