### ISSUE TITLE
Multiple Callback Notification Handler

### ISSUE THREAD

**Issue by yudha-dev** [Midtrans/midtrans-php#74]
Hallo bagaimana mengunakan multiple callback jika ada 2 transaksi..
contoh ada 2 case deposit dan transaksi

**Comment by Andrenzo17** [comment]
Hi @yudha-dev ,

boleh jelaskan dengan lebih detail maksud dari multiple callback jika ada 2 transaksi?
Dari Midtrans sendiri akan mengirimkan http notif setiap perubahan notifikasi per order id.
Untuk best practice handle notif bisa refer ke docs berikut https://docs.midtrans.com/en/after-payment/http-notification?id=best-practice-to-handle-notification

Terima kasih

**Comment by Andrenzo17** [comment]
No response from the author, If any general questions, please contact us [here](https://midtrans.com/id/contact-us)

Thank you
