### ISSUE TITLE
v2.2 php -> Shopeepay payment method returns 'something is missing' and URL not found, even if our URL callback is still alive

### ISSUE THREAD

**Issue by firmanserdana** [Midtrans/midtrans-php#75]
All other payment methods are okay, but then when we use Shopeepay, the FE side gets this notification
![image](https://user-images.githubusercontent.com/56091175/195976344-928f4ed2-a74d-4c11-bcab-d854f859462e.png)

it was fine until 2 days ago, tracing it, it seems we get expired status, from the shopeepay endpoint

midtrans and our side are okay though
![image](https://user-images.githubusercontent.com/56091175/195976397-1491380c-a0e5-490b-a6b1-e52367718a41.png)

should updating the dependency solve the issue, if not, why we don't get any notification if 2.2 is deprecated?

the CS team was just asking log charge, like what is that? even asking our source code, which not helpful at all 😢 

well thanks for any help

**Comment by Andrenzo17** [comment]
HI @firmanserdana so the issue in here you not receive the http notification right?

I checked for this order id S221015111054 and yes the http notif expired failed to sent because url not found.
I can reproduce the error (404 in Midtrans notification worker, we use this header User-Agent:Veritrans and somehow your endpoint return 404 to us. that’s why notification history says URL not found.

So please check your endpoint.

<img width="1138" alt="Screen Shot 2022-10-17 at 11 12 43" src="https://user-images.githubusercontent.com/83454487/196087952-8783a048-8973-4f3c-a3f9-8049ad624adb.png">

**Comment by firmanserdana** [comment]
Yes but the problem is on shopee side, seems like we miss something, because other payment method works

Normally we would be able to open the shopee app using the deeplink

But sure, we are gonna check it first from our side

Thank you

**Comment by Lionzee** [comment]
> HI @firmanserdana so the issue in here you not receive the http notification right?
> 
> I checked for this order id S221015111054 and yes the http notif expired failed to sent because url not found. I can reproduce the error (404 in Midtrans notification worker, we use this header User-Agent:Veritrans and somehow your endpoint return 404 to us. that’s why notification history says URL not found.
> 
> So please check your endpoint.
> 
> make sure that the Notification URL can be reached from Public Internet. Midtrans cannot send notifications to localhost, URL protected with authorization or password, URL behind VPN, unusual destination port, and so on. You may also need to make sure the [following IP address](https://docs.midtrans.com/en/technical-reference/ip-address?id=notification-ip-address) is not blocked from your infrastructure. If you just want to make sure the notification is authentic, you can implement [Verifying Notification Authenticity section](https://docs.midtrans.com/en/after-payment/http-notification?id=verifying-notification-authenticity) below. https://docs.midtrans.com/en/after-payment/http-notification?id=https-notification-webhooks-of-payment-status
> 
> <img alt="Screen Shot 2022-10-17 at 11 12 43" width="1138" src="https://user-images.githubusercontent.com/83454487/196087952-8783a048-8973-4f3c-a3f9-8049ad624adb.png">

The possible problem is in the other endpoint for getting the deep-link url for shopee payment.
the url is on the first image, do midtrans change the url or might be add some parameter to get the shopee deeplink ?

**Comment by Andrenzo17** [comment]
Hi, 
Could you clarify what action you do on FE when get that error?
Looks like you try to call the redirect_url shopeepay from FE/BE. Which is unexpected. 

The steps to integrate with ShopeePay are given below.
1. Send the [Charge API request](https://api-docs.midtrans.com/#shopeepay-charge-api-request) to Midtrans.
2. Open the redirect url in the response to get redirected to Shopee app.
3. Handle the redirect from Shopee app back to merchant app.
4. Handle notifications 

So you just need open the redirect_url shopeepay. Here is the complete docs https://api-docs.midtrans.com/#shopeepay

**Comment by Lionzee** [comment]
More likely our backend tryin to do http request on this link

```
"actions": [
        {
            "name": "deeplink-redirect",
            "method": "GET",
            "url": "https://wsa.uat.wallet.airpay.co.id/universal-link/wallet/pay?deep_and_deferred=1&token=dFhkbmR1bTBIamhW5n7WPz2OrczCvb8_XiHliB9nROFMVByjtwKMAl6G0Ax0cMr79M4hwjs"
        }
    ]
```

since shopeepay doesnt return the deeplink redirect like gopay did so our backend trying to scrap the link from that URL response. but unfortunately the request give 404.

**Comment by Lionzee** [comment]
if u see on the gojek charge resonse it did have the app deeplink but not on shopee.

```
{
            "name": "deeplink-redirect",
            "method": "GET",
            "url": "gojek://gopay/merchanttransfer?tref=1509110800474199656LMVO&amount=10000&activity=GP:RR&callback_url=someapps://callback?order_id=SAMPLE-ORDER-ID-01"
        },
```

**Comment by Lionzee** [comment]
i do double opening the link directly on the mobile phone the link is already works as a deeplink, 

so it kinda solve our problem now

**Comment by Andrenzo17** [comment]
Yes correct, the link should be open via mobile phone.
Thanks

**Comment by Lionzee** [comment]
is that possible to get the direct deeplink with shopee/  

like the one on gopay response? so it doesnt hv tobe redirected to browser first?

**Comment by Andrenzo17** [comment]
Is not possible, the charge response will be contain  ShopeePay universal link. 

Also currently on Gopay charge response we give response with universal link too.

**Comment by firmanserdana** [comment]
@Andrenzo17 since when the changes (universal deeplink) are applied?

**Comment by Andrenzo17** [comment]
The Gopay Universal Link Changes starting on 23 August 2022. 
AFAIK, we already info all merchant about the changes Gopay Universal link via email.

**Comment by firmanserdana** [comment]
What about the shopee ones?

**Comment by Lionzee** [comment]
I still found the gopay payment is still using the direct link with gojek/ prefix.

![image](https://user-images.githubusercontent.com/33141747/196234712-b1a8c95e-4325-4e63-b299-d098c6757064.png)

**Comment by Andrenzo17** [comment]
> What about the shopee ones?

Since a long time ago we already return charge response ShopeePay with universal link. 

> I still found the gopay payment is still using the direct link with gojek/ prefix.

Screenshot you attach above is universal link.
Previously API response from Midtrans is `gojek://` deeeplink and since 23 August 2022 we replace with new `https://gojek.link/` universal link.

**Comment by Andrenzo17** [comment]
No response from the author, If any general questions, please contact us [here](https://midtrans.com/id/contact-us)

Thank you
