### ISSUE TITLE
Is there a way to get transaction expiry time?

### ISSUE THREAD

**Issue by Firman95** [Midtrans/midtrans-php#77]

**Comment by Andrenzo17** [comment]
Hi @Firman95 could you more explain for the question?
Does you mean is payment details **expired time** via API?

Currently API get transaction status is not return the param expired time https://docs.midtrans.com/en/after-payment/get-status?id=get-status-api-requests

You can see the expired time via Dashboard Midtrans (attached pic)
<img width="628" alt="Screen Shot 2022-11-08 at 12 30 43" src="https://user-images.githubusercontent.com/83454487/200482896-814929fa-aa75-49ae-a008-72fa55a0b3a7.png">

Or if you using SNAP, you can open the snap URL again. That will be **Pay with in** 
<img width="431" alt="Screen Shot 2022-11-08 at 12 32 55" src="https://user-images.githubusercontent.com/83454487/200483183-176048a3-bb15-418e-94f3-30403ce21c83.png">

Thank you

**Comment by Firman95** [comment]
Yes I want to get expired time via API, not via dashboard or SNAP. Is there any API that returns expired time of a transaction?

**Comment by Andrenzo17** [comment]
Unfortunately, currently not any API on Midtrans that return expired time. 
Thank you

**Comment by Andrenzo17** [comment]
FYI you can define expiry via API params when you create the transaction. So you can set your own expiry limit and save on your Database without API get status to Midtrans.

Here is the docs to set custom expiry via API https://docs.midtrans.com/en/core-api/advanced-features?id=custom-transaction-expiry

**Comment by Firman95** [comment]
I knew about the other way around, I was just wondering if there is an API that returns the expired time to make the process more simple for my case. Thanks for the reply!
