### ISSUE TITLE
Midtrans Error (401): Operation is not allowed due to unauthorized payload.

### ISSUE THREAD

**Issue by enrinal** [Midtrans/midtrans-php#8]
Saya sudah config semua server_key, client_key, isProduction sudah false.

Tetapi kenapa masih kena error ini ketika notification handler

**Comment by rizdaprasetya** [comment]
`401` karena `server_key` salah, kosong atau tidak sesuai dengan env `isProduction`.

> Saya sudah config semua server_key, client_key, isProduction sudah false.
Sayangnya tidak ada yg bisa menjamin hal tersebut. Coba retrieve ulang serverKey dari Dashboard Midtrans.

Atau silahkan bisa cek sample code:
https://github.com/Midtrans/midtrans-php/blob/master/examples/notification-handler.php

**Comment by enrinal** [comment]
Solved!
Salah urutan code.
