### ISSUE TITLE
sanbox snap ui gopay error 

### ISSUE THREAD

**Issue by ndriodna** [Midtrans/midtrans-php#80]
di sanbox error ketika milih pembayaran gopay tetapi untuk pembayaran menggunakan credit card berhasil 

![image](https://user-images.githubusercontent.com/27008469/209453189-e17bc3ba-efab-42d0-b38c-d88e8a6e3513.png)

token di passing ke front end vue 3

![image](https://user-images.githubusercontent.com/27008469/209453253-0d25ea4a-52b0-4621-81da-7547c5e864c2.png)

**Comment by rizdaprasetya** [comment]
Hi @ndriodna dari evidence dan hasil cek kami:
- Issue bukan karena kesalahan implementasi di sisi Anda.
- Issue ada di akun Midtrans anda, yg menyebabkan issue internal di backend product Snap kami.
- Issue karena keliahatannya ada yg tidak lengkap ketika akun Sandbox Anda didaftarkan/dicreate.

Solusi:
- Sudah kami bantu reset akun Sandboxnya, kami test akun tersebut sudah bisa dipakai transaksi QRIS normal via Snap.

Silahkan coba kembali. Terima kasih.

Tips: Untuk response yang lebih cepat, silahkan hubungi kami via menu Contact Us di website midtrans.com . Dimana ada team Support yang standby menjawab pertanyaan. Sedangkan Github Issue belum tentu dicek berkala oleh tim kami.

**Comment by ndriodna** [comment]
qr code sudah muncul mau nge test pembayaran di simulator error 
![image](https://user-images.githubusercontent.com/27008469/209553939-87edb5ad-2855-488f-b4ed-c6383bd22d5f.png)

**Comment by Andrenzo17** [comment]
HI @ndriodna untuk pembayaran QRIS sandbox maka diharuskan untuk menggunakan QRIS simulator.
Silakan menggunakan simulator dengan link berikut https://simulator.sandbox.midtrans.com/qris/index

Terima kasih

**Comment by ndriodna** [comment]
oke terima kasih sudah bisa
