### ISSUE TITLE
err_unknown_url_scheme android gojek web view (non php)

### ISSUE THREAD

**Issue by ifvodeky24** [Midtrans/midtrans-php#81]
Hi, ingin bertanya. 

Saat ini saya menggunakan deeplink gopay untuk pembayaran di android web view. Di device type samsung saat intent berhasil pindah dari aplikasi saya ke aplikasi gojek, namun saat test menggunakan device type xiaomi terjadi kesalahan err_unknown_url_scheme. Berikut kode yang saya gunakan berdasarkan link [https://docs.midtrans.com/en/other/faq/technical?id=on-ios-device-why-gopay-deeplink-redirects-the-customer-to-different-app-other-than-gojek](url)

```
private boolean handleWebviewCustomUri(final Uri uri) {
    final String url = uri.toString();
    
    // detect these specified universal-urls/deeplinks to be handled by OS
    if (url.contains("gojek://") 
      || url.contains("//gojek.link") 
      || url.contains("shopeeid://") 
      || url.contains("//wsa.wallet.airpay.co.id")
      || url.contains("//tmrwbyuobid.page.link")
    ) 
    {
        final Intent intent = new Intent(Intent.ACTION_VIEW, uri);
        startActivity(intent);
        // `true` means for the specified url, will be handled by OS by starting Intent
        return true;
    } else {
        // `false` means any other url will be loaded normally by the WebView
        return false;
    }
}
```

Saya juga sudah mengetest menggunakan URL [https://tiny.cc/gj-deeplink-test](url) untuk mengecek blocking dari device xiaomi tersebut, tapi berjalan normal dan aplikasi gojek terbuka. Apakah ada yang bisa membantu saya?

Thank you

**Comment by rizdaprasetya** [comment]
Mau menambahkan, @ifvodeky24 
- Ketika mendapat: `err_unknown_url_scheme`, boleh share full log atau screenshotnya? biasanya akan terlihat URL apa yg kena blocking, seperti contoh gambar berikut https://i.stack.imgur.com/8pdrw.jpg.
  - Yang perlu kita pastikan adalah, apakah benar URL deeplink App Gojek yang kena block, ataukah URL lainnya.

> Saya juga sudah mengetest menggunakan URL https://tiny.cc/gj-deeplink-test untuk mengecek blocking dari device xiaomi tersebut, tapi berjalan normal dan aplikasi gojek terbuka.
- Url tersebut dibuka via browser ya? berarti mengindikasikan deeplink jika dibuka dari browser akan normal. Nah yang perlu kamu test, coba buka URL tersebut via WebView dari dalam App kamu, kemudian di tampilan WebViewnya coba click URL yg tampil di page tersebut. Kalau hasilnya kena `err_unknown_url_scheme`, berarti config/implementasi code WebView kamu yang masih perlu disesuaikan.

Thanks.

**Comment by ifvodeky24** [comment]
Hi @rizdaprasetya ,

**Comment by ifvodeky24** [comment]
Hi @rizdaprasetya,

- Untuk poin 1: Berikut capture dari error di webview nya : [https://pasteboard.co/j7i94bkCLxQY.png](url)

- Untuk poin 2: Sudah dicoba code dengan url tersebut di device samsung dan berhasil, untuk xiaomi sedang progress nanti di update. Berikut tampilan implementasi code web view:

`private void loadUrl(String url) {
        binding.webviewPayment.setVisibility(View.VISIBLE);

        WebSettings settings = binding.webviewPayment.getSettings();
        settings.setDomStorageEnabled(true);

        binding.webviewPayment.setWebViewClient(new MyWebViewClient());
        binding.webviewPayment.getSettings().setJavaScriptEnabled(true);
        binding.webviewPayment.getSettings().setDomStorageEnabled(true);
        binding.webviewPayment.getSettings().setJavaScriptCanOpenWindowsAutomatically(true);
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            binding.webviewPayment.getSettings().setSafeBrowsingEnabled(true);
        }
        binding.webviewPayment.loadUrl("https://tiny.cc/gj-deeplink-test");
    }

    private void initEvent() {
        binding.toolbarCloseView.setOnCloseClickListener(v -> onBackPressed());
    }

    class MyWebViewClient extends WebViewClient {
        @Override
        public void onPageStarted(WebView view, String url, Bitmap favicon) {
            if (url.startsWith(finishUrl)) {
                Intent intent = new Intent(TeleconsultationPaymentWebViewActivity.this, TeleconsultationPaymentSuccessActivity.class);
                intent.putExtra(ConstantManager.USER_EMAIL, userEmail);
                intent.putExtra(ConstantManager.PARAM_DELIVERY_TYPE, deliveryType);
                startActivity(intent);
            }
        }

        @Override
        public boolean shouldOverrideUrlLoading(WebView view, WebResourceRequest request) {
            final Uri uri = request.getUrl();
            return handleWebviewCustomUri(uri);
        }


        @Override
        public void onReceivedError(WebView view, WebResourceRequest request, WebResourceError error) {
            super.onReceivedError(view, request, error);
            Log.d("tag", "cekk error" + error.toString());
        }
    }

    private boolean handleWebviewCustomUri(final Uri uri) {
        final String url = uri.toString();

        // detect these specified universal-urls/deeplinks to be handled by OS
        if (url.contains("gojek://")
                || url.contains("//gojek.link")
                || url.contains("shopeeid://")
                || url.contains("//wsa.wallet.airpay.co.id")
                || url.contains("//tmrwbyuobid.page.link")
        ) {
            final Intent intent = new Intent(Intent.ACTION_VIEW, uri);
            startActivity(intent);
            // `true` means for the specified url, will be handled by OS by starting Intent
            return true;
        } else {
            // `false` means any other url will be loaded normally by the WebView
            return false;
        }
    }`

Ada kemungkinan lain lagi? Thank you

**Comment by Andrenzo17** [comment]
Hi @ifvodeky24 

Jika saya  liat dari screenshot imagenya URL yg dibuka beda. Ini order-id test Telechat-F0cx-230104
URL universal link yg dibuka terus error https://pasteboard.co/j7i94bkCLxQY.png
`intent://gopay_xxxx`
Sedangkan, response dari req charge
`https://gojek.link/gopay/merchanttransfer?tref=0420230104015417wdA1oN5iZeID&amount=15000&activity=GP:RR&callback_url=https%3A%2F%2Fpayment.siloamhospitals.com%2Fpayment-processed%3Forder_id%3DTelechat-F0cx-230104`

karena urlnya berubah maka mendapatkan **err_unknown_url_scheme**.
Pastikan untuk tidak mengubah / modif url response yang diberikan ya.

Dari sisi Anda bisa coba test open universal link di bawah ini langsung dari webview nya. 
`https://gojek.link/gopay/merchanttransfer?tref=0420230104015417wdA1oN5iZeID&amount=15000&activity=GP:RR&callback_url=https%3A%2F%2Fpayment.siloamhospitals.com%2Fpayment-processed%3Forder_id%3DTelechat-F0cx-230104`

Terima kasih

**Comment by ifvodeky24** [comment]
Hi @Andrenzo17 , terimakasih masukannya. saya coba dulu ya, boleh kah untuk link request charge tersebut di hide atau didelete?

Thank you

**Comment by ifvodeky24** [comment]
Ternyata penyebabnya device xiaomi masih nge cache aplikasi versi lama, udah solved. Thank you.

**Comment by rizdaprasetya** [comment]
Thanks infonya & sudah share konklusinya mas 👍  Baru tau juga ada case seperti itu ya ternyata dari sisi Devicenya.
