### ISSUE TITLE
Error: Trying to get property 'status_code' of non-object

### ISSUE THREAD

**Issue by rmdhfz** [Midtrans/midtrans-php#83]
Hi Midtrans Team,
I got error Trying to get property 'status_code' of non-object when calling /status.

A PHP Error was encountered
Severity: Notice
Message: Trying to get property 'status_code' of non-object
Filename: Midtrans/ApiRequestor.php
Line Number: 102

![image](https://user-images.githubusercontent.com/39754741/224883630-eff8510a-675d-4b00-a4ed-85c7716ab18f.png)

**Comment by Andrenzo17** [comment]
Hi @rmdhfz could you help to make sure again value isProduction, serverKey and orderId values is already correct? make sure your order id struktur not have special character which can make invalid URL. If there is an special character you can try  API Get Transaction status using transactions id from Midtrans.

Thank you

**Comment by feriirawan89** [comment]
Artinya apa ??

Pada tanggal Rab, 15 Mar 2023 12.57, Andre S ***@***.***>
menulis:

**Comment by Andrenzo17** [comment]
> I got error Trying to get property 'status_code' of non-object when calling /status.
> 
> A PHP Error was encountered Severity: Notice Message: Trying to get property 'status_code' of non-object

There was a similar issue in [here](https://github.com/Midtrans/midtrans-php/issues/45#issuecomment-808258844)
the issue because not set general setting before sent request to Midtrans such as serverKey, isProduction, dan isSanitized.. 

Could you help to follow and read the discussion on that open issue?
Thank you

**Comment by rmdhfz** [comment]
Hi @Andrenzo17 ,
The error is not configuration key value.

This is direct request to: (No Error)
https://api.midtrans.com/v2/xxxx/status
![image](https://user-images.githubusercontent.com/39754741/225802330-6495281a-574f-4ca9-86c8-5a6e0faa493a.png)

The error from request from PHP Midtrans Library (Error, see the screenshot ^^)

**Comment by Andrenzo17** [comment]
> The error is not configuration key value.
> 
> The error from request from PHP Midtrans Library (Error, see the screenshot ^^)

Yes correct, the issue is not your server key and client key wrong.
So please make sure to set config php value before sending get status to Midtrans.

**Comment by rmdhfz** [comment]
Hi @Andrenzo17 ,
I can confirm that the php configuration is correct

**Comment by Andrenzo17** [comment]
Could you share the evidence that show your config are correct? 
please share the sample code or file when you try get API status or at least the screenshot.

i already inform you to make sure to set the config PHP value per function like this https://github.com/Midtrans/midtrans-php/issues/45#issuecomment-808258844 or you can see another example in here https://github.com/Midtrans/midtrans-php/blob/master/examples/core-api/transaction-manipulation.php

Thank you

**Comment by rmdhfz** [comment]
Closed ?

**Comment by rmdhfz** [comment]
Hi @Andrenzo17 

Apakah kamu tidak melihat screenshot ini ?
https://github.com/Midtrans/midtrans-php/issues/83#issuecomment-1473052135

**Comment by Andrenzo17** [comment]
Hi @rmdhfz i waiting your reply, not seeing after 4 days.
yes I see the screenshot, but screenshot above is from POSTMAN right? not from your code PHP Config. 
Nothing wrong with your key, because you can get status directly via POSTMAN.

the issue is probably your PHP config is not correct. 
Do you follow my suggestion above, please?

> i already inform you to make sure to set the config PHP value per function like this https://github.com/Midtrans/midtrans-php/issues/45#issuecomment-808258844 or you can see another example in here https://github.com/Midtrans/midtrans-php/blob/master/examples/core-api/transaction-manipulation.php

**Comment by rmdhfz** [comment]
No, My PHP Config is correct. 
Can you check the code in the following information: 

Filename: Midtrans/Api Request.php 
Line Number: 102

**Comment by Andrenzo17** [comment]
```
Filename: Midtrans/Api Request.php
Line Number: 102
```

Nothing wrong with the code https://github.com/Midtrans/midtrans-php/blob/master/Midtrans/ApiRequestor.php#L102
on line Number 102 the code is related ** Authorization** so likely the config is not correct.

Could you try our example code in here https://github.com/Midtrans/midtrans-php/blob/master/examples/core-api/transaction-manipulation.php ? 

I just try to run our example code, and works as expected. Here is I attach the screenshot
<img width="1165" alt="Screenshot 2023-03-28 at 10 24 24" src="https://user-images.githubusercontent.com/83454487/228119851-d469fdcb-43f0-4e67-bfd3-f5aa8d52e8aa.png">
