### ISSUE TITLE
Preferensi SNAP tidak bekerja

### ISSUE THREAD

**Issue by rmdhfz** [Midtrans/midtrans-php#85]
Dear Midtrans Team,
Saya menemukan kejanggalan saat membuat transaksi snap. 
Berikut adalah preferensi snap saya:

![image](https://github.com/Midtrans/midtrans-php/assets/39754741/b5579af2-893f-43a4-92ba-77dfb8822e70)

Berikut hasilnya:

![image](https://github.com/Midtrans/midtrans-php/assets/39754741/cd12c54a-fbfe-42d3-91e1-a0d817943d9e)

Hasil dari snap tidak sesuai dengan preferensi yang sudah saya set di dashboard.

Mohon bantuannya,
Terima kasih.

**Comment by Andrenzo17** [comment]
Hi @rmdhfz 

kalau di cek SNAP yang digunakan SNAP redirect, dimana untuk settingan SNAP Preference hanya berlaku untuk SNAP pop up saja. Jika ingin mengubah theme dan display name pada SNAP Redirect bisa masuk ke link berikut https://dashboard.midtrans.com/settings/vtweb_preference

Terima kasih
