### ISSUE TITLE
Midtrans API is returning API error. HTTP status code: 404 API response: {"status_code":"404","status_message":"Transaction doesn't exist.","id":"7d69bcb8-1339-4d48-80b4-c287b1466dec"}

### ISSUE THREAD

**Issue by daviddprtma** [Midtrans/midtrans-php#94]
Halo selamat malam. Saya melakukan proses pembayaran dengan menggunakan midtrans di metode sandbox akan tetapi saya mendapatkan pesan error yang mengatakan bahwa "Transaction doesn't exist" padahal di database saya terdapat percobaan transanksi menggunakan mode sandbox dan juga ada snap_tokennya. Berikut ini adalah screenshot dari error beserta dengan code saya yang terdapat dibawah ini: 

    public function pembayaranSukses(Request $request, Transaction $transaction){
        Config::$serverKey = config('midtrans.server_key');
        Config::$isProduction = false;
        Config::$isSanitized = true;
        Config::$is3ds = true;
        if($transaction->status(200) == 'capture'){

            $transaction = Payment::where('snap_token', $request->order_id)->first();
            $transaction->status = 'success';
            $transaction->update();
        }

        return view('price.successPembayaranBasic');
    }
   
   Bagaimana ya solusinya? Terima kasih

![image](https://github.com/Midtrans/midtrans-php/assets/76859181/98f54c65-401d-4d9e-9c15-17daaf531674)

![midtrans db](https://github.com/Midtrans/midtrans-php/assets/76859181/20ce66bd-de3a-4b07-9ada-7811f14e021e)

**Comment by vaniawahyu** [comment]
`order_id` berbeda dengan snap token. 
Untuk `order_id` biasanya dibuat secara unique tiap transaksi. ([link](https://docs.midtrans.com/reference/json-objects#transaction-details-object)) `order_id` ini bisa dicek pada dashboard midtrans untuk menentukan apakah order ada atau tidak.
Sedangkan untuk snap token memang dihasilkan secara otomatis oleh midtrans. Token ini bisa digunakan untuk membuka kembali halaman pembayaran jika masa waktu expired belum habis ([link](https://docs.midtrans.com/reference/expire-a-snap-session#set-a-custom-expiry-for-the-snap-page-only-default-is-24-hours)).
Jadi error tersebut disebabkan karena `order_id` tidak ada di midtrans.

**Comment by daviddprtma** [comment]
> `order_id` berbeda dengan snap token. Untuk `order_id` biasanya dibuat secara unique tiap transaksi. ([link](https://docs.midtrans.com/reference/json-objects#transaction-details-object)) `order_id` ini bisa dicek pada dashboard midtrans untuk menentukan apakah order ada atau tidak. Sedangkan untuk snap token memang dihasilkan secara otomatis oleh midtrans. Token ini bisa digunakan untuk membuka kembali halaman pembayaran jika masa waktu expired belum habis ([link](https://docs.midtrans.com/reference/expire-a-snap-session#set-a-custom-expiry-for-the-snap-page-only-default-is-24-hours)). Jadi error tersebut disebabkan karena `order_id` tidak ada di midtrans.


makasih kak utk penjelasannya. udh solved masalah ini kak😊
